# Site settings

title: Gregarious Mammal
email: info@gregariousmammal.com
description: Social Technology
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregariousmammal.com"
twitter_username: chrischinch
github_username:  chrischinchilla
permalink: /:title
comments: true
exclude: [Gemfile]

gems: ['redcarpet']
exclude: ['Gemfile', 'Gemfile.lock', 'vendor']

pagination:
  per_page: 25
  limit: false

collections:
  meetme:
    output: true
  podcast:
    output: true
    layout: podcast

picture:
  source: /images
  output: generated
  markup: picture
  presets:
    default:
      # ppi: [1, 1.5]
      attr:
        class: default-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    categories:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 450
      source_default:
        width: 200
    article:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 350
        # height: 200
      source_default:
        width: 350
    service:
      ppi: [1, 1.5, 2]
      attr:
        class: service
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 200
        # height: 200
      source_default:
        width: 200
    mediumscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 400
      source_default:
        width: 400
    smallscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: small-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 100
        # height: 200
      source_default:
        width: 100
    listings:
      ppi: [1, 1.5, 2]
      attr:
        class: listings
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 300
      source_default:
        width: 300

# Build settings
markdown: redcarpet
