# Site settings
title: Gregarious Mammal
email: info@gregariousmammal.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregariousmammal.com" # the base hostname & protocol for your site
twitter_username: chrischinch
github_username:  chrischinchilla
permalink: /:title
comments: true

picture:
  source: /images
  output: generated
  markup: picture
  presets:
    default:
      # ppi: [1, 1.5]
      attr:
        class: default-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    categories:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        height: 200
      source_default:
        height: 200
    article:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 200
        # height: 200
      source_default:
        width: 200
    mediumscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 200
      source_default:
        width: 200
    smallscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: small-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 100
        # height: 200
      source_default:
        width: 100
    listings:
      ppi: [1, 1.5, 2]
      attr:
        class: listings
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 125
      source_default:
        width: 125

# Build settings
markdown: redcarpet
