# Site settings
title: Gregarious Mammal
email: info@gregariousmammal.com
description:  Technology and Education.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregariousmammal.com" # the base hostname & protocol for your site
twitter_username: chrischinch
github_username:  chrischinchilla
permalink: /:title
comments: true
paginate: 15

collections:
  presentations:
    output: true
  events:
    output: true
    layout: event

defaults:
  -
    scope:
      type: presentations
    values:
      url: http://presentations.gregariousmammal.com

picture:
  source: /images
  output: generated
  markup: picture
  presets:
    default:
      # ppi: [1, 1.5]
      attr:
        class: default-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    categories:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        height: 200
      source_default:
        height: 200
    article:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 200
        # height: 200
      source_default:
        width: 200
    service:
      ppi: [1, 1.5, 2]
      attr:
        class: service
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 300
        # height: 200
      source_default:
        width: 300
    mediumscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: medium-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 200
      source_default:
        width: 200
    smallscreen:
      ppi: [1, 1.5, 2]
      attr:
        class: small-screen
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 100
        # height: 200
      source_default:
        width: 100
    listings:
      ppi: [1, 1.5, 2]
      attr:
        class: listings
        itemprop: image
      source_medium:
        media: "(min-width: 40em)"
        width: 125
      source_default:
        width: 125

# Build settings
markdown: redcarpet
