baseURL = "https://gregariousmammal.com"
languageCode = "en-au"
title = "Gregarious Mammal"
theme = "ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en-GB"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-59452354-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  # description = "The last theme you'll ever need. Maybe."
  facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = "https://www.linkedin.com/company/gregarious-mammal/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 20
